export const lessons = [
  {
    id: 1,
    slug: "computer-hardware",
    title: "Computer Hardware",
    shortTitle: "Computer Hardware",
    icon: "🖥️",
    color: "#0d3b4e",
    description:
      "Explore the physical components that make up a computer system—from CPUs and RAM to storage drives and motherboards. Understand how hardware components interact and influence overall system performance.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["CPU Architecture", "Memory (RAM)", "Storage Devices", "Motherboards", "I/O Interfaces"],
    href: "#lesson-1",
  },
  {
    id: 2,
    slug: "number-system",
    title: "Number System",
    shortTitle: "Number System",
    icon: "🔢",
    color: "#D43828",
    description:
      "Dive into the mathematical foundations of computing. Learn binary, octal, decimal, and hexadecimal systems and how computers use them to represent and process all kinds of data.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["Binary", "Hexadecimal", "Octal", "Conversions", "Arithmetic Operations"],
    href: "#lesson-2",
  },
  {
    id: 3,
    slug: "data-formats",
    title: "Data Formats",
    shortTitle: "Data Formats",
    icon: "📄",
    color: "#F27800",
    description:
      "Understand how data is encoded, stored, and transmitted across different systems. From ASCII and Unicode to JSON, XML, and binary formats—learn how format choice impacts compatibility and performance.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["ASCII & Unicode", "JSON & XML", "Binary Formats", "Compression", "Encoding Standards"],
    href: "#lesson-3",
  },
  {
    id: 4,
    slug: "operating-systems",
    title: "Operating Systems",
    shortTitle: "Operating Systems",
    icon: "⚙️",
    color: "#0d3b4e",
    description:
      "Discover the software layer that manages hardware resources and provides services for applications. Explore Windows, Linux, macOS, and mobile OS architectures, process management, and file systems.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["Process Management", "File Systems", "Memory Management", "Linux & Windows", "OS Security"],
    href: "#lesson-4",
  },
  {
    id: 5,
    slug: "computing-platforms",
    title: "Computing Platforms",
    shortTitle: "Computing Platforms",
    icon: "☁️",
    color: "#D43828",
    description:
      "Survey the landscape of computing environments—from personal desktops and servers to cloud infrastructure and edge computing. Understand how platforms shape application deployment and scalability.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["Cloud Computing", "Edge Computing", "Virtualization", "Containers", "HPC"],
    href: "#lesson-5",
  },
  {
    id: 6,
    slug: "database-platforms",
    title: "Database Platforms",
    shortTitle: "Database Platforms",
    icon: "🗄️",
    color: "#F27800",
    description:
      "Learn how organizations store, retrieve, and manage structured and unstructured data. Compare relational databases like MySQL and PostgreSQL with NoSQL platforms such as MongoDB and Redis.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["SQL Databases", "NoSQL", "Data Modeling", "Query Optimization", "Database Security"],
    href: "#lesson-6",
  },
  {
    id: 7,
    slug: "storage-platforms",
    title: "Storage Platforms",
    shortTitle: "Storage Platforms",
    icon: "💾",
    color: "#0d3b4e",
    description:
      "Examine how data is physically and logically stored across different media and systems. From traditional HDDs and SSDs to object storage and distributed file systems like HDFS and Amazon S3.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["HDD & SSD", "RAID Systems", "Object Storage", "Cloud Storage", "NAS & SAN"],
    href: "#lesson-7",
  },
  {
    id: 8,
    slug: "application-platforms",
    title: "Application Platforms",
    shortTitle: "Application Platforms",
    icon: "📦",
    color: "#D43828",
    description:
      "Understand the platforms and runtime environments that power modern applications—from PaaS solutions like Heroku and AWS Elastic Beanstalk to serverless platforms and microservices frameworks.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["PaaS", "Serverless", "Microservices", "Docker & Kubernetes", "CI/CD Pipelines"],
    href: "#lesson-8",
  },
  {
    id: 9,
    slug: "web-platforms",
    title: "Web Platforms",
    shortTitle: "Web Platforms",
    icon: "🌐",
    color: "#F27800",
    description:
      "Explore the technologies and platforms that power the World Wide Web. Understand web servers, protocols, hosting platforms, CDNs, and the stack behind modern web applications and APIs.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["HTTP/HTTPS", "Web Servers", "REST & GraphQL", "CDNs", "Web Frameworks"],
    href: "#lesson-9",
  },
  {
    id: 10,
    slug: "content-management-systems",
    title: "Content Management Systems",
    shortTitle: "CMS",
    icon: "📝",
    color: "#0d3b4e",
    description:
      "Learn how CMS platforms like WordPress, Drupal, and headless CMS solutions enable teams to create, manage, and publish digital content without deep programming knowledge.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["WordPress", "Headless CMS", "Drupal", "Strapi", "Content Modeling"],
    href: "#lesson-10",
  },
  {
    id: 11,
    slug: "media-platforms",
    title: "Media Platforms",
    shortTitle: "Media Platforms",
    icon: "🎬",
    color: "#D43828",
    description:
      "Investigate the infrastructure behind audio, video, and image delivery platforms. Understand streaming protocols, media encoding, digital asset management, and platforms like YouTube and Vimeo.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["Video Streaming", "Audio Platforms", "Transcoding", "CDN for Media", "DAM Systems"],
    href: "#lesson-11",
  },
  {
    id: 12,
    slug: "analytics",
    title: "Analytics",
    shortTitle: "Analytics",
    icon: "📊",
    color: "#F27800",
    description:
      "Discover how businesses extract insights from data using analytics platforms. From Google Analytics to Apache Spark and Power BI, learn about data pipelines, dashboards, and business intelligence.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["Business Intelligence", "Data Visualization", "Big Data", "ETL Pipelines", "Reporting Tools"],
    href: "#lesson-12",
  },
  {
    id: 13,
    slug: "artificial-intelligence",
    title: "Artificial Intelligence",
    shortTitle: "AI",
    icon: "🤖",
    color: "#0d3b4e",
    description:
      "Explore the platforms and frameworks driving the AI revolution—from machine learning libraries like TensorFlow and PyTorch to cloud AI services from Google, AWS, and Microsoft Azure.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["Machine Learning", "Deep Learning", "NLP", "Computer Vision", "AI Cloud Services"],
    href: "#lesson-13",
  },
  {
    id: 14,
    slug: "security",
    title: "Security",
    shortTitle: "Security",
    icon: "🔐",
    color: "#D43828",
    description:
      "Study the principles and platforms that protect digital systems from threats. Understand cybersecurity frameworks, encryption, identity management, firewalls, and security operations tools.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["Cryptography", "Network Security", "IAM", "SIEM Platforms", "Zero Trust"],
    href: "#lesson-14",
  },
  {
    id: 15,
    slug: "internet-of-things",
    title: "Internet of Things (IoT)",
    shortTitle: "IoT",
    icon: "📡",
    color: "#F27800",
    description:
      "Learn how connected devices, sensors, and embedded systems communicate and process data. Explore IoT platforms like AWS IoT Core, Azure IoT Hub, and the protocols powering smart devices.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["IoT Architecture", "MQTT Protocol", "Edge Processing", "Smart Devices", "IoT Security"],
    href: "#lesson-15",
  },
  {
    id: 16,
    slug: "mobile-apps-and-game-platforms",
    title: "Mobile Apps & Game Platforms",
    shortTitle: "Mobile & Games",
    icon: "🎮",
    color: "#0d3b4e",
    description:
      "Explore mobile development ecosystems (iOS, Android) and game platforms (Unity, Unreal Engine, Steam). Understand app stores, game engines, monetization strategies, and cross-platform development.",
    image: "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
    topics: ["iOS & Android", "React Native", "Unity & Unreal", "App Stores", "Game Monetization"],
    href: "#lesson-16",
  },
];
